# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
# development:
#   adapter: async
development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || 'redis://red-d1uv83mr433s73f5n0fg:6379/1' %>
  
production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || 'redis://red-d1uv83mr433s73f5n0fg:6379/1' %>
  channel_prefix: wellness_api_production
