development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || 'redis://red-d1uv83mr433s73f5n0fg:6379' %>
  channel_prefix: wellness_api_production
