default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: secret
  # password: wellness
  # host: 127.0.0.1  # <-- 127.0.0.1 for local 
  host: db  # <-- this must match the container name or service name in docker-compose
  port: 5432
  pool: 5

development:
  <<: *default
  database: wellnessdatabase # wellness for Docker
  # database: wellness # wellness for local

# test:
#   <<: *default
#   database: wellness_test

# production:
#   <<: *default
#   database: wellness_production
